"""initial

Revision ID: d2e846ed10a8
Revises: 
Create Date: 2026-03-18 15:58:02.541060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e846ed10a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)

    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('duracao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('preco_custo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('preco_venda', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('produtos_categoria_id_fkey'), 'produtos', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('produtos_fornecedor_id_fkey'), 'produtos', 'fornecedores', ['fornecedor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.create_index(op.f('idx_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_index(op.f('idx_produtos_fornecedor'), 'produtos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('idx_produtos_categoria'), 'produtos', ['categoria_id'], unique=False)
    op.drop_column('produtos', 'fornecedor')
    op.drop_column('produtos', 'preco')
    op.drop_column('produtos', 'quantidade')
    op.drop_column('produtos', 'categoria')
    op.create_table('itens_venda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venda_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), sa.Computed('((quantidade)::numeric * preco_unitario)', persisted=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantidade > 0', name=op.f('itens_venda_quantidade_check')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('itens_venda_produto_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('itens_venda_venda_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('itens_venda_pkey'))
    )
    op.create_index(op.f('idx_itens_venda_venda'), 'itens_venda', ['venda_id'], unique=False)
    op.create_index(op.f('idx_itens_venda_produto'), 'itens_venda', ['produto_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clientes_pkey'))
    )
    op.create_index(op.f('idx_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_movimentacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['entrada'::character varying, 'saida'::character varying]::text[])", name=op.f('movimentacoes_estoque_tipo_check')),
    sa.CheckConstraint('quantidade > 0', name=op.f('movimentacoes_estoque_quantidade_check')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('movimentacoes_estoque_produto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('movimentacoes_estoque_pkey'))
    )
    op.create_index(op.f('idx_movimentacoes_produto'), 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('idx_movimentacoes_data'), 'movimentacoes_estoque', ['data_movimentacao'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_contratacao', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('funcionarios_pkey'))
    )
    op.create_table('vendas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_venda', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('vendas_cliente_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('vendas_funcionario_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('vendas_pkey'))
    )
    op.create_index(op.f('idx_vendas_data'), 'vendas', ['data_venda'], unique=False)
    op.create_index(op.f('idx_vendas_cliente'), 'vendas', ['cliente_id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fornecedores_pkey')),
    sa.UniqueConstraint('cnpj', name=op.f('fornecedores_cnpj_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('estoque',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('localizacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estoque_minimo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('estoque_maximo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantidade >= 0', name=op.f('estoque_quantidade_check')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('estoque_produto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estoque_pkey'))
    )
    op.create_index(op.f('idx_estoque_produto'), 'estoque', ['produto_id'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categorias_pkey')),
    sa.UniqueConstraint('nome', name=op.f('categorias_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    # ### end Alembic commands ###
