from .produto import Produto
from .servico import Servico
from .cliente import Cliente
from .telefone import Telefone
from .endereco import Endereco
from .venda import Venda
from .item_venda import ItemVenda
from .estoque import Estoque
from .categoria import Categoria
from .fabricante import Fabricante
from .fornecedor import Fornecedor